config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'credits#index'

  resources :artists
  resources :credits

  get "artists/new" => 'artist#new', :as => :newartist
  
end

app/models/credit.rb
class Credit < ApplicationRecord
  validates :song_title, presence: true

  has_many :artists_credits
  has_many :artists, through: :artists_credits
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
    before_action :authenticate_user!, :except => [:show, :index]
    
    def index
        @credits = Credit.all
    end

    def create
        @credit = Credit.new(credit_params)

        @credit.save

        if @credit.save
            flash[:success] = 'The credit has been added!'
            redirect_to credits_path
        else
            format.html { render 'form' }
            format.json { render json: @credit.errors, status: :unprocessable_entity }
        end
       
        
    end

    def new
        @credit = Credit.new
        @artist = Artist.new    

    end

    def edit 
        @credit = Credit.find(params[:id])
    end

    def show 
        @credit = Credit.find(params[:id])
    end

    def update
        credit = Credit.find(params[:id])
        credit.update(credit_params)
        
        redirect_to credits_path
    end

    def destroy
        Credit.destroy(params[:id])
        redirect_to credits_path
    end

    private
    def credit_params
        params.require(:credit).permit(:song_title,:mix_version, artist_ids: [])
    end




end

app/helpers/credits_helper.rb
module CreditsHelper

    def artists_for_select
        Artist.all.collect { |i| [i.artist_name, i.id] }
    end

end

app/views/credits/_form.html.erb
<%= form_for @credit do |f| %>

    <div>
        <%= f.label "Song Title" %>
        <%= f.text_field :song_title, class: 'form-control' %>
    </div>

    <div>
        <%= f.label "Mix Version" %>
        <%= f.text_field :mix_version, class: 'form-control' %>
    </div>

    <div>
        <%= f.label "Artist Name" %>
        <%= f.select :artist_ids, options_for_select(artists_for_select), {}, multiple: "true", class: "form-control", id: 'select_two' %>
        <p class="text-right"><%= link_to 'Add New Artists', new_artist_path, data: {toggle: 'modal', target: '#exampleModal'} %> </p>
        
    </div>

    <br>
    <div>   
        <%= f.submit "Submit", class: 'btn btn-light' %>
    </div>

<% end %>

app/views/credits/index.html.erb
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <br>
            
            <%= link_to 'Create New Credit', new_credit_path, class: "btn btn-outline-dark" %>

            <br><br>

            <% @credits.each do |disp| %>
            
                <div class="song_title">
                    <a class="nav-link" href="<%= credit_path(disp) %>">
                    <%= disp.song_title %>
                        <% if disp.mix_version? %> 
                            (<%= disp.mix_version %>) 
                        <% end %> 
                    </a>
                </div>

                <div class="artist_info">
                    by 
                    <% disp.artists.each do |artist|%>
                        <%= artist.artist_name %> 
                    <% end %> <br>
                </div>
                
            <% end %>

        </div>
    </div>
</div>

app/views/credits/new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <br>
      <h3>Create New Credits</h3>
            
      <%= render "form" %>

      <!-- Modal -->

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
              <%#---  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>  ---%>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            <div class="modal-body">
                
              <%= render partial: "artists/form", locals: { url: new_artist_path, modalname: "#exampleModal", remote: "true" }  %>

            </div>
          
          </div>
        </div>
      </div>

    <!-- Modal -->



    </div>
  </div>
</div>

app/views/credits/show.html.erb
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-6"> 
            <br>
            
                <h1> 
                    <%= @credit.song_title %> 
                </h1>
                <h2>
                    <% @credit.artists.each do |artist| %>
                        <%= artist.artist_name %> 
                    <% end %>
                </h2>
               
        </div>
    </div>
</div>